# Generated by Django 3.2 on 2021-08-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='person_responsible',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
